### ISSUE TITLE
Is it possible to run in debug mode?

### ISSUE THREAD

**Issue by tiagostutz** [test-runner-js/test-runner#1]
I was trying to debug on VSCode a test using test-runner but I couldn't make it. I have googled for some directions but couldn't find any on test-runner, just on node and npm, which I tried, but with no success, as I'm using the test-runner executable and the `--inspector-brk` is not allowed to be passed to it.
Any directions on how to do it?

BTW, the test I'm building is for the PR of this issue: https://github.com/lwsjs/lws/issues/13

**Comment by 75lb** [comment]
Wrote some instructions here: 

https://github.com/test-runner-js/test-runner/wiki/How-to-debug-a-test-in-Chrome-DevTools
